# This is a basic workflow to help you get started with Actions

name: CIFullStack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-front-end"
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/checkoutcalculator
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup Node.js 14
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          
      - name: Installing dependencies
        run: npm install
        
      - name: Testing
        run: npm run test:unit
        
      - name: Building
        run: npm run build
        
      - run: echo "Done CI for frontend."
        
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java 16
        uses: actions/setup-java@v2.3.1
        with: 
          java-version: 16
          distribution: 'temurin'
          
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Tesing
        run: sh mvnw -B test
      
      - name: Building
        run: sh mvnw -B clean package
        
      - run: echo "Done CI for backend."
